# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-07 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fye', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.BooleanField(default=0, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=10, verbose_name='name'),
        ),
    ]
